# Basics of NumPy

In [1]:
import numpy as np

## Creating a NumPy Array

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


## Getting Attributes of a NumPy Array

In [4]:
# Get dimension
a.ndim

1

In [5]:
# Get shape
b.shape

(2, 3)

In [6]:
# Get type
a.dtype

dtype('int32')

In [7]:
# Get size
a.itemsize

4

In [8]:
# Get total size
a.nbytes

12

## Accessing/Changing a NumPy Array

In [9]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# Get a specific element [row, column]
a[1, 5]
# You can also use negative indices [1, -2] in this case

13

In [11]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [13]:
# Getting a bit more fancy [start_index : end_index : step_size]
a[0, 1:6:2]

array([2, 4, 6])

In [14]:
# Modifiying an element
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [15]:
# Modifying a column
a[:, 2] = [98, 99]
print(a)

[[ 1  2 98  4  5  6  7]
 [ 8  9 99 11 12 20 14]]


## 3D NumPy Arrays

In [16]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# Get specific element (work outside in)
b[0, 1, 1]

4

In [18]:
# Modifying
b[:, 1, :] = [[9, 9], [8, 8]]

## Initializing Different Types of NumPy Arrays

In [20]:
# All 0's matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# All 1's matrix
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [23]:
# Any other number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [24]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [25]:
# Random decimal numbers
np.random.rand(4, 2)

array([[0.18981441, 0.69879662],
       [0.22752814, 0.9057874 ],
       [0.12122923, 0.59667702],
       [0.19844208, 0.24893209]])

In [26]:
# Random integer values
np.random.randint(7, size=(3, 3))

array([[4, 6, 2],
       [2, 0, 6],
       [6, 1, 6]])

In [28]:
# Square array
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
# Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


## Excercise

In [38]:
output = np.ones((5, 5))

z = np.zeros((3, 3))
z[1, 1] = 9

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!

In [39]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


# Mathematics